/*
 * DK Maternity Lexicon Api
 * This is the specification of the DK Maternity Lexicon API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.sds.nsp.maternity.lexicon.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * The validation error descriptor. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-03T11:09:06.852462+01:00[Europe/Copenhagen]")
public class ProblemDetailsInvalidparams {

  @JsonProperty("path")
  private String path = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("reason")
  private String reason = null;
  public ProblemDetailsInvalidparams path(String path) {
    this.path = path;
    return this;
  }

  

  /**
  * Get path
  * @return path
  **/
  public String getPath() {
    return path;
  }
  public void setPath(String path) {
    this.path = path;
  }
  public ProblemDetailsInvalidparams name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public ProblemDetailsInvalidparams reason(String reason) {
    this.reason = reason;
    return this;
  }

  

  /**
  * Get reason
  * @return reason
  **/
  public String getReason() {
    return reason;
  }
  public void setReason(String reason) {
    this.reason = reason;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProblemDetailsInvalidparams problemDetailsInvalidparams = (ProblemDetailsInvalidparams) o;
    return Objects.equals(this.path, problemDetailsInvalidparams.path) &&
        Objects.equals(this.name, problemDetailsInvalidparams.name) &&
        Objects.equals(this.reason, problemDetailsInvalidparams.reason);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(path, name, reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProblemDetailsInvalidparams {\n");
    
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
