openapi: 3.0.0

info:
  title: Common Domain Model
  description: Common Domain Model for Facade APIs
  version: 1.0.0

paths: {}

components:
  schemas:
    uuidv4:
      title: Universally Unique IDentifier version 4
      description: >
        A Universally Unique IDentifier (UUID) version 4.
        See [RFC 4122, section 4.4](https://tools.ietf.org/html/rfc4122#section-4.4)
      type: string
      pattern: '[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'
      example: 'dfa66499-40b7-4bc6-a2e5-dd3cbcd8cf68'

    uuidv5:
      title: Universally Unique IDentifier version 5
      description: >
        A Universally Unique IDentifier (UUID) version 5.
        See [RFC 4122, section 4.3](https://tools.ietf.org/html/rfc4122#section-4.3)
      type: string
      pattern: '[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'
      example: '8da3af4b-176e-5f53-bab2-a2b349e5229d'

    cprNumber:
      title: Danish national person identifier
      type: string
      pattern: '([06][1-9]|[1-25-8][0-9]|[39][0-1])(0[1-9]|1[0-2])[0-9]{6}'
      example: '9103672134'
