openapi: 3.0.0

info:
  title: Appointment Domain Model
  description: Appointment Domain Model for Maternity Facade API
  version: 1.0.0
  license:
    name: MIT License
    url: https://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/LICENSE

paths: {}

components:
  schemas:
    EditableAppointment:
      description: represents the fields users/the frontend can edit. Maybe look here for help with implementation https://www.nspop.dk/display/ESP/Indhold+og+forretningsregler+Aftaleoversigt
      type: object
      properties:
        title:
          type: string
        reason:
          type: string
        period:
          type: object
          properties:
            start:
              type: string
              format: date-time
            end:
              type: string
              format: date-time
            type:
              description: decides if the time is fixed (i.e. appointment lasts from start to end), a guide (i.e. we can't promise we'll show up at that exact time) or an interval (i.e. the appointment will happen some-time with in this interval)
              type: string
              enum: [fixed, guide, interval]
          required: [start, type]
        repeated:
          type: boolean
          description: true if this appointment is part of a repeating pattern
        location:
          type: object
          properties:
            address:
              type: object
              properties:
                street:
                  type: string
                city:
                  type: string
                postalCode:
                  type: string
            phone:
              type: string
            name:
              type: string
            description:
              type: string
        responsible:
          type: object
          description: The practitioner/organization who has the patient responsibility with regards to this appointment
          properties:
            id:
              type: string
            name:
              type: string
            type:
              type: string
              enum: [practitioner, organization]
          required: [id, name, type]
        performer:
          type: object
          description: The practitioner/organization who should actually participate in this appointment
          properties:
            id:
              type: string
            name:
              type: string
            type:
              type: string
              enum: [practitioner, organization]
          required: [id, name, type]
      required: [responsible, performer, location, period, title]
    Appointment:
      allOf:
        - $ref: '#/components/schemas/EditableAppointment'
        - type: object
          properties:
            id:
              type: string
          required: [id]

