openapi: 3.0.0
info:
  title: DK Maternity Session API
  description: This is the specification of the DK Maternity Session API
  version: 1.0.0
  license:
    name: MIT License
    url: https://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/LICENSE

security:
    - application:
        - read
        - write

paths:
  /session:
    get:
      summary: Get Userinformation
      description: >
        Returns User information for the current session
      responses:
        '200':
          description: User Context Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserContext'
components:
  schemas:
    UserContext:
      title: Represent a saml user
      properties:
        commonName:
          type: string
        organizationName:
          type: string
        role:
          type: string
