/*
 * Care Plan Domain Model
 * Care Plan Domain Model for Maternity Facade API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.sds.nsp.maternity.data.care_plan.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * Code
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-26T12:45:02.145373+01:00[Europe/Copenhagen]")
public class Code {

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("codeSystem")
  private String codeSystem = null;

  @JsonProperty("display")
  private String display = null;
  public Code code(String code) {
    this.code = code;
    return this;
  }

  

  /**
  * Get code
  * @return code
  **/
  public String getCode() {
    return code;
  }
  public void setCode(String code) {
    this.code = code;
  }
  public Code codeSystem(String codeSystem) {
    this.codeSystem = codeSystem;
    return this;
  }

  

  /**
  * Get codeSystem
  * @return codeSystem
  **/
  public String getCodeSystem() {
    return codeSystem;
  }
  public void setCodeSystem(String codeSystem) {
    this.codeSystem = codeSystem;
  }
  public Code display(String display) {
    this.display = display;
    return this;
  }

  

  /**
  * Get display
  * @return display
  **/
  public String getDisplay() {
    return display;
  }
  public void setDisplay(String display) {
    this.display = display;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Code code = (Code) o;
    return Objects.equals(this.code, code.code) &&
        Objects.equals(this.codeSystem, code.codeSystem) &&
        Objects.equals(this.display, code.display);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, codeSystem, display);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Code {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    codeSystem: ").append(toIndentedString(codeSystem)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
