/*
 * Care Plan Domain Model
 * Care Plan Domain Model for Maternity Facade API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.sds.nsp.maternity.data.care_plan.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EditableCarePlan
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-26T12:45:02.145373+01:00[Europe/Copenhagen]")
public class EditableCarePlan {

  @JsonProperty("patient")
  private String patient = null;

  @JsonProperty("activities")
  private List<EditableActivity> activities = null;

  @JsonProperty("processId")
  private String processId = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("goal")
  private Goal goal = null;

  @JsonProperty("responsibleOrganization")
  private ResponsibleOrganization responsibleOrganization = null;
  public EditableCarePlan patient(String patient) {
    this.patient = patient;
    return this;
  }

  

  /**
  * Get patient
  * @return patient
  **/

  public String getPatient() {
    return patient;
  }
  public void setPatient(String patient) {
    this.patient = patient;
  }

  public EditableCarePlan activities(List<EditableActivity> activities) {
    this.activities = activities;
    return this;
  }

  public EditableCarePlan addActivitiesItem(EditableActivity activitiesItem) {
    if (this.activities == null) {
      this.activities = new ArrayList<EditableActivity>();
    }
    this.activities.add(activitiesItem);
    return this;
  }

  /**
   * Get activities
   * @return activities
   **/
  public List<EditableActivity> getActivities() {
    return activities;
  }
  public void setActivities(List<EditableActivity> activities) {
    this.activities = activities;
  }
  

  /**
  * A reference to any external clinical pathway that this care plan is a part of
  * @return processId
  **/

  public String getProcessId() {
    return processId;
  }
  public void setProcessId(String processId) {
    this.processId = processId;
  }
  public EditableCarePlan title(String title) {
    this.title = title;
    return this;
  }

  

  /**
  * Get title
  * @return title
  **/

  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  public EditableCarePlan description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/

  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public EditableCarePlan goal(Goal goal) {
    this.goal = goal;
    return this;
  }

  

  /**
  * Get goal
  * @return goal
  **/

  public Goal getGoal() {
    return goal;
  }
  public void setGoal(Goal goal) {
    this.goal = goal;
  }
  public EditableCarePlan responsibleOrganization(ResponsibleOrganization responsibleOrganization) {
    this.responsibleOrganization = responsibleOrganization;
    return this;
  }

  

  /**
  * Get responsibleOrganization
  * @return responsibleOrganization
  **/

  public ResponsibleOrganization getResponsibleOrganization() {
    return responsibleOrganization;
  }
  public void setResponsibleOrganization(ResponsibleOrganization responsibleOrganization) {
    this.responsibleOrganization = responsibleOrganization;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditableCarePlan editableCarePlan = (EditableCarePlan) o;
    return Objects.equals(this.patient, editableCarePlan.patient) &&
        Objects.equals(this.activities, editableCarePlan.activities) &&
        Objects.equals(this.processId, editableCarePlan.processId) &&
        Objects.equals(this.title, editableCarePlan.title) &&
        Objects.equals(this.description, editableCarePlan.description) &&
        Objects.equals(this.goal, editableCarePlan.goal) &&
        Objects.equals(this.responsibleOrganization, editableCarePlan.responsibleOrganization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(patient, activities, processId, title, description, goal, responsibleOrganization);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditableCarePlan {\n");
    
    sb.append("    patient: ").append(toIndentedString(patient)).append("\n");
    sb.append("    activities: ").append(toIndentedString(activities)).append("\n");
    sb.append("    processId: ").append(toIndentedString(processId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    goal: ").append(toIndentedString(goal)).append("\n");
    sb.append("    responsibleOrganization: ").append(toIndentedString(responsibleOrganization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
