/*
 * Care Plan Domain Model
 * Care Plan Domain Model for Maternity Facade API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.sds.nsp.maternity.data.care_plan.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EditableActivityLocation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-26T12:45:02.145373+01:00[Europe/Copenhagen]")
public class Location {

  @JsonProperty("healthCareActorsIdentification")
  private String healthCareActorsIdentification = null;

  @JsonProperty("organizationName")
  private String organizationName = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("fax")
  private String fax = null;
  public Location healthCareActorsIdentification(String healthCareActorsIdentification) {
    this.healthCareActorsIdentification = healthCareActorsIdentification;
    return this;
  }

  

  /**
  * Get healthCareActorsIdentification
  * @return healthCareActorsIdentification
  **/
  public String getHealthCareActorsIdentification() {
    return healthCareActorsIdentification;
  }
  public void setHealthCareActorsIdentification(String healthCareActorsIdentification) {
    this.healthCareActorsIdentification = healthCareActorsIdentification;
  }
  public Location organizationName(String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  

  /**
  * Get organizationName
  * @return organizationName
  **/
  public String getOrganizationName() {
    return organizationName;
  }
  public void setOrganizationName(String organizationName) {
    this.organizationName = organizationName;
  }
  public Location phone(String phone) {
    this.phone = phone;
    return this;
  }

  

  /**
  * Get phone
  * @return phone
  **/
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }
  public Location email(String email) {
    this.email = email;
    return this;
  }

  

  /**
  * Get email
  * @return email
  **/
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }
  public Location fax(String fax) {
    this.fax = fax;
    return this;
  }

  

  /**
  * Get fax
  * @return fax
  **/
  public String getFax() {
    return fax;
  }
  public void setFax(String fax) {
    this.fax = fax;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location editableActivityLocation = (Location) o;
    return Objects.equals(this.healthCareActorsIdentification, editableActivityLocation.healthCareActorsIdentification) &&
        Objects.equals(this.organizationName, editableActivityLocation.organizationName) &&
        Objects.equals(this.phone, editableActivityLocation.phone) &&
        Objects.equals(this.email, editableActivityLocation.email) &&
        Objects.equals(this.fax, editableActivityLocation.fax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(healthCareActorsIdentification, organizationName, phone, email, fax);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditableActivityLocation {\n");
    
    sb.append("    healthCareActorsIdentification: ").append(toIndentedString(healthCareActorsIdentification)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
