/*
 * Care Plan Domain Model
 * Care Plan Domain Model for Maternity Facade API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.sds.nsp.maternity.data.care_plan.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * EditableActivityPractitioner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-26T12:45:02.145373+01:00[Europe/Copenhagen]")
public class Practitioner {

  @JsonProperty("healthCareActorsIdentification")
  private String healthCareActorsIdentification = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("organizationName")
  private String organizationName = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("fax")
  private String fax = null;
  public Practitioner healthCareActorsIdentification(String healthCareActorsIdentification) {
    this.healthCareActorsIdentification = healthCareActorsIdentification;
    return this;
  }

  /**
  * Get healthCareActorsIdentification
  * @return healthCareActorsIdentification
  **/
  public String getHealthCareActorsIdentification() {
    return healthCareActorsIdentification;
  }
  public void setHealthCareActorsIdentification(String healthCareActorsIdentification) {
    this.healthCareActorsIdentification = healthCareActorsIdentification;
  }
  public Practitioner firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  

  /**
  * Get firstName
  * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }
  public Practitioner lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

  

  /**
  * Get lastName
  * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }
  public Practitioner organizationName(String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  

  /**
  * Get organizationName
  * @return organizationName
  **/
  public String getOrganizationName() {
    return organizationName;
  }
  public void setOrganizationName(String organizationName) {
    this.organizationName = organizationName;
  }
  public Practitioner phone(String phone) {
    this.phone = phone;
    return this;
  }

  

  /**
  * Get phone
  * @return phone
  **/
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }
  public Practitioner email(String email) {
    this.email = email;
    return this;
  }

  

  /**
  * Get email
  * @return email
  **/
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }
  public Practitioner fax(String fax) {
    this.fax = fax;
    return this;
  }

  

  /**
  * Get fax
  * @return fax
  **/
  public String getFax() {
    return fax;
  }
  public void setFax(String fax) {
    this.fax = fax;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Practitioner practitioner = (Practitioner) o;
    return Objects.equals(this.healthCareActorsIdentification, practitioner.healthCareActorsIdentification) &&
        Objects.equals(this.firstName, practitioner.firstName) &&
        Objects.equals(this.lastName, practitioner.lastName) &&
        Objects.equals(this.organizationName, practitioner.organizationName) &&
        Objects.equals(this.phone, practitioner.phone) &&
        Objects.equals(this.email, practitioner.email) &&
        Objects.equals(this.fax, practitioner.fax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(healthCareActorsIdentification, firstName, lastName, organizationName, phone, email, fax);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditableActivityPractitioner {\n");
    
    sb.append("    healthCareActorsIdentification: ").append(toIndentedString(healthCareActorsIdentification)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
