/*
 * Care Plan Domain Model
 * Care Plan Domain Model for Maternity Facade API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.sds.nsp.maternity.data.care_plan.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * EditableCarePlanResponsibleOrganization
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-26T12:45:02.145373+01:00[Europe/Copenhagen]")
public class ResponsibleOrganization {

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("source")
  private String source = null;
  public ResponsibleOrganization id(String id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/

  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  public ResponsibleOrganization source(String source) {
    this.source = source;
    return this;
  }

  

  /**
  * Get source
  * @return source
  **/

  public String getSource() {
    return source;
  }
  public void setSource(String source) {
    this.source = source;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsibleOrganization responsibleOrganization = (ResponsibleOrganization) o;
    return Objects.equals(this.id, responsibleOrganization.id) &&
        Objects.equals(this.source, responsibleOrganization.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, source);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditableCarePlanResponsibleOrganization {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
