/*
 * Observation Domain Model
 * Observation (measurement) Domain Model for Maternity Facade API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.sds.nsp.maternity.data.observation.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ObservationType
 */
public enum ObservationType {
  WEIGHT("weight"),
  BLOOD_PREASSURE("blood_preassure"),
  URINE("urine"),
  EDEMA("edema"),
  PUBIS_MEASURUEMENTS("pubis_measuruements"),
  FETUS_ACTIVITY("fetus_activity"),
  FETUS_GENDER("fetus_gender"),
  FETUS_PRESENTATION("fetus_presentation"),
  GA_U_D("ga_u_d"),
  UL_WEIGHT("ul_weight"),
  WEIGHT_DEVIATION("weight_deviation"),
  AMNIOTIC_FLUID("amniotic_fluid"),
  FLOW("flow");

  private String value;

  ObservationType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ObservationType fromValue(String text) {
    for (ObservationType b : ObservationType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
