openapi: 3.0.0
info:
  version: 1.0.0
  title: DK Maternity Feedback Api
  description: This is the specification of the DK Maternity Feedback API.

paths:
  /feedback:
    post:
      summary: Create feedback
      description: >
        Post feedback from current user identified in the **context** cookie
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedbackResponse'
        '500':
          description: >
            Internal Server Error -
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  schemas:
    Uuidv4:
      title: Universally Unique IDentifier version 4
      description: >
        A Universally Unique IDentifier (UUID) version 4.
        See [RFC 4122, section 4.4](https://tools.ietf.org/html/rfc4122#section-4.4)
      type: string
      pattern: '[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'
      example: 'dfa66499-40b7-4bc6-a2e5-dd3cbcd8cf68'
    Feedback:
      type: object
      properties:
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string
      required: [ rating ]
    FeedbackResponse:
      allOf:
        - $ref: '#/components/schemas/Feedback'
        - type: object
          properties:
            identifier:
              $ref: '#/components/schemas/Uuidv4'
          required:
            - identifier
    ProblemDetails:
      title: Problem Details for HTTP APIs
      description: >
        A way to carry machine-readable details of errors in a HTTP response to avoid the need to
        define new error response formats for HTTP APIs. See [RFC7807](https://tools.ietf.org/rfc/rfc7807.txt)
      type: object
      required:
        - type
      properties:
        type:
          description: >
            A URI reference [RFC3986](https://tools.ietf.org/rfc/rfc3986.txt) that identifies the problem type.
          type: string
          format: uri
        title:
          description: >
            A short, human-readable summary of the problem type.
          type: string
        status:
          description: >
            The HTTP status code [([RFC7231], Section 6)](https://tools.ietf.org/rfc/rfc7231.txt#section-6)
            generated by the origin server for this occurrence of the problem.
          type: number
        instance:
          description: >
            A URI reference that identifies the specific occurrence of the problem.
          type: string
        detail:
          description: >
            A human-readable explanation specific to this occurrence of the problem.
          type: string
        debugging:
          description: >
            Debugging information for DEV and QA environments.
          type: string
        invalid-params:
          description: >
            An array of validation errors.
          type: array
          items:
            description: >
              The validation error descriptor.
            type: object
            required:
              - path
              - name
              - reason
            properties:
              path:
                type: string
              name:
                type: string
              reason:
                type: string
            additionalProperties: false
          uniqueItems: true
      additionalProperties: false
