/*
 * Appointment Domain Model
 * Appointment Domain Model for Maternity Facade API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.sds.nsp.maternity.data.appointment.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * EditableAppointmentLocationAddress
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-29T11:02:03.592754+01:00[Europe/Copenhagen]")
public class AppointmentLocationAddress {

  @JsonProperty("street")
  private String street = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("postalCode")
  private String postalCode = null;
  public AppointmentLocationAddress street(String street) {
    this.street = street;
    return this;
  }

  

  /**
  * Get street
  * @return street
  **/
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }
  public AppointmentLocationAddress city(String city) {
    this.city = city;
    return this;
  }

  

  /**
  * Get city
  * @return city
  **/
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }
  public AppointmentLocationAddress postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  

  /**
  * Get postalCode
  * @return postalCode
  **/
  public String getPostalCode() {
    return postalCode;
  }
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppointmentLocationAddress appointmentLocationAddress = (AppointmentLocationAddress) o;
    return Objects.equals(this.street, appointmentLocationAddress.street) &&
        Objects.equals(this.city, appointmentLocationAddress.city) &&
        Objects.equals(this.postalCode, appointmentLocationAddress.postalCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(street, city, postalCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditableAppointmentLocationAddress {\n");
    
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
