openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/trifork-nsp/maternity-facade-api/1.0.0
info:
  version: "1.0.0"
  title: DK Maternity Facade API
  description: >
    This is the specification of the DK Maternity Facade API.
    It is a facade for the Web Services Resource Transfer DK Maternity API.
security:
  - application:
      - read
      - write
paths:
  /maternity/data-card:
    parameters:
      - in: cookie
        name: context
        required: true
        schema:
          $ref: '#/components/schemas/sessionContext'
    get:
      summary: Get data cards
      description: >
        Gets all data cards for the current patient identified in the **context** cookie.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/DataCardResponse'
        '206':
          description: >
            Partial Content -
          content:
            application/json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/DataCardResponse'
        '401':
          description: >
            Unauthorized -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
        '500':
          description: >
            Internal Server Error -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
    post:
      summary: Create a data card
      description: >
        Creates a new data card for the current patient identified in the **context** cookie.
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/CreateDataCardRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/DataCardResponse'
        '206':
          description: >
            Partial Content -
          content:
            application/json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/DataCardResponse'
        '401':
          description: >
            Unauthorized -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
        '500':
          description: >
            Internal Server Error -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
  /maternity/data-card/{identifier}:
    parameters:
      - in: path
        name: identifier
        schema:
          $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/Uuidv4'
        required: true
        description: The identifier of the data card
    get:
      summary: Get a specific data card
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/DataCardResponse'
        '206':
          description: >
            Partial Content -
          content:
            application/json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/DataCardResponse'
        '401':
          description: >
            Unauthorized -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
        '500':
          description: >
            Internal Server Error -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
    put:
      summary: Update a specific data card
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/UpdateDataCardRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/DataCardResponse'
        '206':
          description: >
            Partial Content -
          content:
            application/json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/maternity-facade-api/src/main/resources/open-api/maternity-domain-model.yaml#/components/schemas/DataCardResponse'
        '401':
          description: >
            Unauthorized -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
        '500':
          description: >
            Internal Server Error -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
    delete:
      summary: Delete a specific data card
      responses:
        '200':
          description: OK
        '401':
          description: >
            Unauthorized -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
        '500':
          description: >
            Internal Server Error -
          content:
            application/problem+json:
              schema:
                $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/ProblemDetails'
components:
  schemas:
    sessionContext:
      title: Session context
      description: >
        The patient and application mode encoded as a JWT
      type: object
      properties:
        header:
          type: object
          properties:
            alg:
              type: string
              enum: [HS256]
            typ:
              type: string
              enum: [JWT]
          required:
            - alg
            - typ
        payload:
          type: object
          properties:
            patient-identifier:
              $ref: 'http://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/common/src/main/resources/open-api/common-facade-api.yaml#/components/schemas/CprNumber'
            application-mode:
              $ref: '#/components/schemas/ApplicationMode'
          required:
            - patient-identifier
            - application-mode
        signature:
          description: The signature of the JWT
          type: string
          minLength: 44
          maxLength: 44
      required:
        - header
        - payload
        - signature
      example: >
        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
        eyJwYXRpZW50LWlkZW50aWZpZXIiOiI5MTAzNjcyMTM0IiwiYXBwbGljYXRpb24tbW9kZSI6InN0YW5kYWxvbmUifQ.
        mu7vIUndSNn83ziXypl6zBaeI51ogCRetjS8ChOYDpc

    ApplicationMode:
      type: string
      enum: [ standalone, embedded ]

  securitySchemes:
    application:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources