openapi: 3.0.0

info:
  title: Demographics Domain Model
  description: Demographics Domain Model for Maternity Facade API
  version: 1.0.0
  license:
    name: MIT License
    url: https://raw.githubusercontent.com/trifork/dk-maternity-facade-api/master/LICENSE

paths: {}

components:
  schemas:
    Demographics:
      type: object
      properties:
